stages:
  - convert-images
  - build-hugo
  - add-index
  - deploy-swas

转换图片:
  stage: convert-images
  tags:
    - docker
  image: reprover/markdown-image-uploader
  variables:
    ACCESS_KEY: $ALIYUN_OSS_ACCESSKEY_ID
    ACCESS_SECRET: $ALIYUN_OSS_ACCESSKEY_SECRET
    ENDPOINT: $ALIYUN_OSS_ENDPOINT
    BUCKET_NAME: $BUCKET_NAME
    CLIENT_NAME: $CLIENT_NAME
    VISIT_URL: $VISIT_URL
  script:
    - uploader "${CI_PROJECT_DIR}/content"
  artifacts:
    paths:
      - content

编译Hugo:
  stage: build-hugo
  tags:
    - docker
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  image: xdevbase/hugo-builder:latest
  script:
    - hugo --minify
  artifacts:
    paths:
      - public

上传algolia索引:
  stage: add-index
  tags:
    - docker
  image: python:latest
  variables:
    ALGOLIA_INDEX_ID: $ALGOLIA_INDEX_ID
    ALGOLIA_INDEX_ADMIN_KEY: $ALGOLIA_INDEX_ADMIN_KEY
    ALGOLIA_INDEX_NAME: $ALGOLIA_INDEX_NAME
    INDEX_PATH: $INDEX_PATH
    GITHUB_WORKSPACE: $CI_PROJECT_DIR
  before_script:
    - wget https://raw.githubusercontent.com/rxrw/algolia-index-uploader/main/main.py
    - pip install algoliasearch
  script:
    - python3 main.py $INDEX_PATH
  retry:
    max: 2
    when: always

部署到阿里轻量云服务器:
  stage: deploy-swas
  tags:
    - docker
  image: alpine
  before_script:
    - apk update && apk add --no-cache openssh-client rsync
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
    - echo "${SSH_HOST_KEY}" > /etc/ssh/ssh_known_hosts
  script:
    - ssh-add ~/.ssh/id_rsa
    - rsync -r public/* $SSH_USER@$SSH_HOST:/var/www/html
  environment:
    name: production
    url: https://rxrw.me
