name: Deploy Hugo Site to Github Pages on Master Branch

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2  # v2 does not have submodules option now
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: '0.80.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }} # 这里的 ACTIONS_DEPLOY_KEY 则是上面设置 Private Key的变量名
          external_repository: rxrw/rxrw.github.io # Pages 远程仓库 
          publish_dir: "./public"
          keep_files: true # remove existing files
          publish_branch: built  # deploying branch
          commit_message: ${{ github.event.head_commit.message }}
          
#       - name: Add Algolia Indexer
#         uses: darrenjennings/algolia-docsearch-action@v0.1.0
#         with:
#           algolia_application_id: ${{ secrets.ALGOLIA_APPID }}
#           algolia_api_key: ${{ secrets.ALGOLIA_ADMIN_KEY }}
#           file: 'algolia.json'
